//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionix.POS.Core.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiKey
    {
        public string ApiKey1 { get; set; }
        public string Company { get; set; }
        public string Branch { get; set; }
        public string User { get; set; }
    
        public virtual User User1 { get; set; }
    }
}
