//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionix.POS.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiKeyAppSetting
    {
        public string ApiKey { get; set; }
        public string Serie { get; set; }
        public Nullable<long> SaleTicket { get; set; }
        public Nullable<long> IsPOSCredit { get; set; }
        public Nullable<long> PurchaseReference { get; set; }
        public Nullable<long> IsBusinessNameVisible { get; set; }
        public Nullable<long> IsTaxAddressVisible { get; set; }
        public Nullable<long> IsClientVisible { get; set; }
        public Nullable<long> BulkSales { get; set; }
        public Nullable<long> UseTare { get; set; }
    
        public virtual ApiKey ApiKey1 { get; set; }
    }
}
