//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionix.POS.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchOffice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BranchOffice()
        {
            this.ApiKeys = new HashSet<ApiKey>();
            this.CashMovements = new HashSet<CashMovement>();
            this.VCompanyRelationships = new HashSet<VCompanyRelationship>();
        }
    
        public string Branch { get; set; }
        public string Company { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public string Description { get; set; }
        public string Street { get; set; }
        public string OutsideNo { get; set; }
        public string InsideNo { get; set; }
        public string Colony { get; set; }
        public string Location { get; set; }
        public string Municipality { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public long IsActive { get; set; }
        public long IsDeleted { get; set; }
        public long IsDefault { get; set; }
        public long RegisterDate { get; set; }
        public string Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApiKey> ApiKeys { get; set; }
        public virtual BranchOfficeType BranchOfficeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashMovement> CashMovements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VCompanyRelationship> VCompanyRelationships { get; set; }
    }
}
