//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionix.POS.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMBackOfficeError
    {
        public string Error { get; set; }
        public string Company { get; set; }
        public string Branch { get; set; }
        public string User { get; set; }
        public string Message { get; set; }
        public string StackTrace { get; set; }
        public Nullable<long> RegisterDate { get; set; }
    }
}
