//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionix.POS.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMCashMovement
    {
        public string Movement { get; set; }
        public string CashMovementType { get; set; }
        public decimal Total { get; set; }
        public string Description { get; set; }
        public long HasVoucher { get; set; }
        public long IsSync { get; set; }
        public long RegisterDate { get; set; }
        public string User { get; set; }
        public string Company { get; set; }
        public string Branch { get; set; }
    
        public virtual PMBranchOffice BranchOffice { get; set; }
        public virtual CashMovementType CashMovementType1 { get; set; }
        public virtual PMVCompanyRelationship VCompanyRelationship { get; set; }
        public virtual PMUser User1 { get; set; }
    }
}
