//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionix.POS.Core.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PMApiKey> PMApiKeys { get; set; }
        public virtual DbSet<PMBackOfficeError> PMBackOfficeErrors { get; set; }
        public virtual DbSet<PMBranchOffice> PMBranchOffices { get; set; }
        public virtual DbSet<PMBranchOfficeType> PMBranchOfficeTypes { get; set; }
        public virtual DbSet<PMCashMovement> PMCashMovements { get; set; }
        public virtual DbSet<CashMovementType> CashMovementTypes { get; set; }
        public virtual DbSet<PMUser> PMUsers { get; set; }
        public virtual DbSet<PMVCompanyRelationship> PMVCompanyRelationships { get; set; }
        public virtual DbSet<PMApiKeyAppSetting> PMApiKeyAppSettings { get; set; }
        public virtual DbSet<PMSynchronizationLog> PMSynchronizationLogs { get; set; }
    }
}
