//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionix.POS.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMSynchronizationLog
    {
        public string ApiKey { get; set; }
        public long LocalRegisterDate { get; set; }
        public long ServerRegisterDate { get; set; }
    
        public virtual PMApiKey ApiKey1 { get; set; }
    }
}
