//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionix.POS.Core.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApiKey> ApiKeys { get; set; }
        public virtual DbSet<BackOfficeError> BackOfficeErrors { get; set; }
        public virtual DbSet<BranchOffice> BranchOffices { get; set; }
        public virtual DbSet<BranchOfficeType> BranchOfficeTypes { get; set; }
        public virtual DbSet<CashMovement> CashMovements { get; set; }
        public virtual DbSet<CashMovementType> CashMovementTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VCompanyRelationship> VCompanyRelationships { get; set; }
        public virtual DbSet<ApiKeyAppSetting> ApiKeyAppSettings { get; set; }
        public virtual DbSet<SynchronizationLog> SynchronizationLogs { get; set; }
    }
}
