//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionix.POS.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCompanyRelationship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VCompanyRelationship()
        {
            this.ApiKeys = new HashSet<ApiKey>();
            this.CashMovements = new HashSet<CashMovement>();
        }
    
        public string Company { get; set; }
        public string Branch { get; set; }
        public string User { get; set; }
        public string Profile { get; set; }
        public string Status { get; set; }
        public string ProfileName { get; set; }
        public string StatusDescription { get; set; }
        public string Rfc { get; set; }
        public string BusinessName { get; set; }
        public string CommercialName { get; set; }
        public string Abbreviation { get; set; }
        public string BranchName { get; set; }
        public string Email { get; set; }
        public string ApiKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApiKey> ApiKeys { get; set; }
        public virtual BranchOffice BranchOffice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashMovement> CashMovements { get; set; }
        public virtual User User1 { get; set; }
    }
}
